name: Run valgrind on binary
description: Run valgrind on binary

inputs:
  artifact:
    description: Artifact to download
    required: false

  binary:
    description: Binary to run
    required: true

  run-args:
    description: Command line arguments passed to the binary
    required: false

  run-env:
    description: Environment variables to set for the binary
    required: false

  workdir:
    description: Working directory to run the binary in
    required: false

runs:
  using: composite
  steps:
    - uses: actions/download-artifact@v6
      if: ${{ inputs.artifact != '' }}
      with:
        name: ${{ inputs.artifact }}

    - name: Run valgrind
      shell: bash
      run: |
        if [ -n "${{ inputs.workdir }}" ]; then
          cd ${{ inputs.workdir }}
        fi

        chmod +x ./${{ inputs.binary }}

        ${{ inputs.run-env }} valgrind --leak-check=full \
          --show-leak-kinds=definite,indirect,possible \
          --fair-sched=yes \
          --track-origins=yes \
          --trace-children=yes \
          --error-markers=errstart,errend \
          ./${{ inputs.binary }} ${{ inputs.run-args }}
